use crate::diagnostics_dto::{
    DecodeQueueDiagnosticsDto, DesktopDiagnosticsDto, IdentityDiagnosticsDto,
    ListenerDiagnosticsDto, MonitorDiagnosticsDto, NotificationBridgeDiagnosticsDto,
    PacketizeQueueDiagnosticsDto, ProfileDiagnosticsDto, StorageDiagnosticsDto,
    SynchronizationDiagnosticsDto, TransportDiagnosticsDto, VersionsDiagnosticsDto,
};
use crate::dto::{
    BridgeLifecycleDto, CoreVersionDto, DesktopErrorDto, MigrationSummaryDto, ProfileSummaryDto,
    StorageInspectionDto, StoredSettingsSummaryDto, TrustedDeviceSummaryDto,
};
use crate::host_session_dto::{
    BroadcastDeliveryDto, ConnectedListenerDto, DeliveryReportDto, HostConnectionDto,
    HostInvitationDto, HostSessionSnapshotDto, PendingJoinRequestDto,
};
use crate::platform::diagnostics_export::DiagnosticsExportOutcome;
use crate::platform::network_dto::{
    MdnsStatusDto, MonitorStatusDto, NetworkAddressCandidateDto, NetworkAddressClassDto,
    NetworkBindPreferenceDto, NetworkBindingDto, NetworkInterfaceSnapshotDto,
    SetNetworkBindPreferenceRequest,
};
use crate::runtime_dto::{
    ApproveJoinRequest, AttachNotificationResponse, AudioSourceSummaryDto, CapabilitySnapshotDto,
    CommandReceiptDto, CoreDiagnosticDto, CoreNotificationDto, CoreSnapshotDto, DiagnosticFieldDto,
    HostDraftDto, HostDraftValidationDto, JoinRequestCommandRequest, ListenerCommandRequest,
    OpenProfileRequest, OpenProfileResponse, PlatformEffectDto, RevisionCommandRequest,
    UpdateHostDraftRequest,
};
use std::fmt;
use ts_rs::{Config, TS};

const GENERATED_HEADER: &str = "// @generated by silent-disco-desktop. Do not edit by hand.\n\n";

/// Renders the complete deterministic TypeScript bridge contract.
///
/// # Errors
///
/// Returns [`BindingGenerationError`] if `ts-rs` panics while rendering a type. The
/// panic is contained so stale or partial bindings never look successful.
pub fn render_typescript_bindings() -> Result<String, BindingGenerationError> {
    std::panic::catch_unwind(render_typescript_bindings_inner)
        .map_err(|_| BindingGenerationError::TypeRendererPanicked)
}

fn render_typescript_bindings_inner() -> String {
    let config = Config::default();
    let declarations = [
        declaration::<CoreVersionDto>(&config),
        declaration::<ProfileSummaryDto>(&config),
        declaration::<DesktopErrorDto>(&config),
        declaration::<MigrationSummaryDto>(&config),
        declaration::<StoredSettingsSummaryDto>(&config),
        declaration::<TrustedDeviceSummaryDto>(&config),
        declaration::<BridgeLifecycleDto>(&config),
        declaration::<StorageInspectionDto>(&config),
        declaration::<OpenProfileRequest>(&config),
        declaration::<RevisionCommandRequest>(&config),
        declaration::<ApproveJoinRequest>(&config),
        declaration::<JoinRequestCommandRequest>(&config),
        declaration::<ListenerCommandRequest>(&config),
        declaration::<UpdateHostDraftRequest>(&config),
        declaration::<NetworkAddressClassDto>(&config),
        declaration::<NetworkAddressCandidateDto>(&config),
        declaration::<NetworkBindPreferenceDto>(&config),
        declaration::<SetNetworkBindPreferenceRequest>(&config),
        declaration::<HostConnectionDto>(&config),
        declaration::<PendingJoinRequestDto>(&config),
        declaration::<ConnectedListenerDto>(&config),
        declaration::<DeliveryReportDto>(&config),
        declaration::<BroadcastDeliveryDto>(&config),
        declaration::<HostSessionSnapshotDto>(&config),
        declaration::<HostInvitationDto>(&config),
        declaration::<MdnsStatusDto>(&config),
        declaration::<MonitorStatusDto>(&config),
        declaration::<NetworkBindingDto>(&config),
        declaration::<NetworkInterfaceSnapshotDto>(&config),
        declaration::<CommandReceiptDto>(&config),
        declaration::<AudioSourceSummaryDto>(&config),
        declaration::<HostDraftDto>(&config),
        declaration::<CapabilitySnapshotDto>(&config),
        declaration::<HostDraftValidationDto>(&config),
        declaration::<CoreSnapshotDto>(&config),
        declaration::<OpenProfileResponse>(&config),
        declaration::<AttachNotificationResponse>(&config),
        declaration::<PlatformEffectDto>(&config),
        declaration::<DiagnosticFieldDto>(&config),
        declaration::<CoreDiagnosticDto>(&config),
        declaration::<CoreNotificationDto>(&config),
        declaration::<VersionsDiagnosticsDto>(&config),
        declaration::<ProfileDiagnosticsDto>(&config),
        declaration::<StorageDiagnosticsDto>(&config),
        declaration::<IdentityDiagnosticsDto>(&config),
        declaration::<TransportDiagnosticsDto>(&config),
        declaration::<ListenerDiagnosticsDto>(&config),
        declaration::<SynchronizationDiagnosticsDto>(&config),
        declaration::<DecodeQueueDiagnosticsDto>(&config),
        declaration::<PacketizeQueueDiagnosticsDto>(&config),
        declaration::<MonitorDiagnosticsDto>(&config),
        declaration::<NotificationBridgeDiagnosticsDto>(&config),
        declaration::<DesktopDiagnosticsDto>(&config),
        declaration::<DiagnosticsExportOutcome>(&config),
    ];

    let mut output = String::from(GENERATED_HEADER);
    for declaration in declarations {
        output.push_str(&declaration);
        output.push_str("\n\n");
    }
    output
}

fn declaration<T: TS>(config: &Config) -> String {
    format!("export type {} = {};", T::name(config), T::inline(config))
}

/// Failure while producing generated frontend bindings.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindingGenerationError {
    TypeRendererPanicked,
}

impl fmt::Display for BindingGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TypeRendererPanicked => {
                formatter.write_str("Rust-to-TypeScript type rendering panicked")
            }
        }
    }
}

impl std::error::Error for BindingGenerationError {}

#[cfg(test)]
mod tests {
    use super::render_typescript_bindings;

    #[test]
    fn output_is_deterministic_and_contains_runtime_contract() {
        let first = render_typescript_bindings().expect("render bindings");
        let second = render_typescript_bindings().expect("render bindings again");
        assert_eq!(first, second);
        assert!(first.starts_with("// @generated"));
        assert!(first.contains("export type BridgeLifecycleDto"));
        assert!(first.contains("export type StorageInspectionDto"));
        assert!(first.contains("export type HostDraftDto"));
        assert!(first.contains("export type UpdateHostDraftRequest"));
        assert!(first.contains("export type ApproveJoinRequest"));
        assert!(first.contains("export type JoinRequestCommandRequest"));
        assert!(first.contains("export type ListenerCommandRequest"));
        assert!(first.contains("export type CommandReceiptDto"));
        assert!(first.contains("export type DeliveryReportDto"));
        assert!(first.contains("export type CoreSnapshotDto"));
        assert!(first.contains("export type OpenProfileResponse"));
        assert!(first.contains("export type AttachNotificationResponse"));
        assert!(first.contains("export type CoreNotificationDto"));
    }

    #[test]
    fn output_does_not_include_secret_key_fields() {
        let output = render_typescript_bindings().expect("render bindings");
        assert!(!output.contains("public_key"));
        assert!(!output.contains("publicKey:"));
        assert!(!output.contains("private_key_ref"));
        assert!(!output.contains("privateKeyRef:"));
        assert!(!output.contains("identitySecret"));
        assert!(output.contains("hasPublicKey"));
        assert!(output.contains("hasPrivateKeyReference"));
    }

    #[test]
    fn notification_contract_is_redacted() {
        let output = render_typescript_bindings().expect("render bindings");
        assert!(output.contains("effectKind"));
        assert!(output.contains("operationId"));
        assert!(!output.contains("privateKey"));
        assert!(!output.contains("nativeHandle"));
    }
}
