//! Lab Mode IPC DTOs (Block 42; spec section 29).
//!
//! Deliberately compiled **unconditionally** -- unlike `crate::lab` and
//! `crate::lab_commands`, which only exist under the `lab-mode` Cargo
//! feature. `desktop-bindings.ts` (generated by `bindings::render_typescript_bindings`,
//! see `bin/generate_bindings.rs`) is produced by `cargo run --bin
//! generate_bindings` with this crate's *default* features, i.e. without
//! `lab-mode` -- if the Lab DTO types themselves were feature-gated, the
//! frontend's `LabScreen.tsx` would have no real generated types to import
//! and `npm run typecheck` would fail on every build, defeating "Rust is
//! the source of truth for IPC DTO shapes" (spec 11.5) for exactly the
//! screen that most needs it. Only the *commands* that produce/consume
//! these DTOs (`crate::lab_commands`) and the runtime they wrap
//! (`crate::lab`) stay behind `lab-mode`, mirroring the precedent already
//! set by `get_lab_mode_available` (`lib.rs`): always compiled, always
//! registered, truthful about compile-time availability rather than
//! merely absent.
//!
//! Every millisecond-valued `u64`/`i64` field is carried as a decimal
//! string, matching this crate's own established convention
//! (`dto::MigrationSummaryDto`'s own doc comment: "Timestamps are strings
//! to preserve u64 precision") rather than a `number`, even though every
//! bound in `lab::scenario` keeps these values far inside `f64`'s safe
//! integer range today -- consistency with the rest of the generated
//! contract is worth more than a locally "safe" shortcut.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// One active Lab node (Block 42 "node list and state panels").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabNodeDto {
    pub node_id: String,
    pub offset_ms: String,
    pub drift_ppm: String,
}

/// One scenario-declared link's fault configuration (Block 42 "fault
/// configuration"). These values are the validated initial receive-fault
/// profile that the live Lab transport will use when the loaded scenario is
/// next run; a later `setLinkFaults` scenario step may deliberately replace
/// them during that run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabLinkDto {
    pub from: String,
    pub to: String,
    pub latency_ms: String,
    pub jitter_ms: String,
    pub loss_permille: u16,
}

/// A validated scenario document's bounded summary (Block 42 "scenario
/// open ... through restricted dialogs").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabScenarioSummaryDto {
    pub schema_version: u32,
    pub seed: String,
    pub node_ids: Vec<String>,
    pub link_count: u32,
    pub fixture_count: u32,
    pub step_count: u32,
    pub assertion_count: u32,
    pub timeout_ms: String,
    pub links: Vec<LabLinkDto>,
}

/// One bounded, redacted timeline entry (Block 42 "bounded event
/// timeline"). A deliberately flattened one-line projection of
/// `lab::recorder::RecordedNotification` -- the full structured trace
/// remains available through "recording export" (Block 41's
/// `ScenarioRecording`); this shape exists only to render a bounded,
/// human-scannable list, not to duplicate the recording format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabTimelineEntryDto {
    pub node: String,
    pub sequence: String,
    /// One of `"snapshot" | "effect" | "transportEffect" | "storageEffect"
    /// | "error" | "diagnostic"`.
    pub kind: String,
    pub summary: String,
}

/// One executed scenario step (Block 42's own presentation of
/// `lab::scenario::StepResult`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabStepResultDto {
    pub index: u32,
    pub at_ms: String,
    pub node: String,
    pub submit_error: Option<String>,
    /// `"settled" | "timedOut"`.
    pub settlement: String,
}

/// One evaluated assertion (Block 42 "assertion results").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabAssertionResultDto {
    pub kind: String,
    pub node: String,
    pub by_ms: String,
    /// `"held" | "timedOut"`.
    pub outcome: String,
}

/// A completed scenario run (Block 42 "start ... controls", "bounded event
/// timeline", "assertion results").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabRunOutcomeDto {
    /// `"completed" | "timedOut" | "executionError"`.
    pub outcome: String,
    pub final_time_ms: String,
    pub step_results: Vec<LabStepResultDto>,
    pub assertion_results: Vec<LabAssertionResultDto>,
    pub timeline: Vec<LabTimelineEntryDto>,
    pub timeline_truncated: bool,
}

/// The complete Lab session state (Block 42 "node list and state panels",
/// "virtual time").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabStateDto {
    pub now_ms: String,
    /// `true` while `lab_run_loaded_scenario` is executing -- gates
    /// "running-state command disablement" (Block 42's own test list).
    pub running: bool,
    /// `true` after a backend pause request has been accepted and until a
    /// resume/stop/completion clears it. Pause is cooperative: the currently
    /// executing scenario step is allowed to settle before the next
    /// deterministic step boundary blocks.
    pub paused: bool,
    pub nodes: Vec<LabNodeDto>,
    pub loaded_scenario: Option<LabScenarioSummaryDto>,
    pub last_run: Option<LabRunOutcomeDto>,
}

/// Distinguishes "the user picked Cancel" from a genuine failure (mirrors
/// `platform::diagnostics_export::DiagnosticsExportOutcome`'s own
/// precedent) for both scenario "save" and recording export.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase", tag = "kind")]
#[ts(rename_all = "camelCase", tag = "kind")]
pub enum LabFileOutcomeDto {
    Saved,
    Cancelled,
}

/// Request DTO for `lab_advance_virtual_time` (Block 42 "step").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabAdvanceTimeRequest {
    pub delta_ms: String,
}

/// Request DTO for `lab_start_node` (Block 42 "start ... controls").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabStartNodeRequest {
    pub offset_ms: String,
    pub drift_ppm: String,
}

/// Request DTO for `lab_stop_node` (Block 42 "stop ... controls").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabStopNodeRequest {
    pub node_id: String,
}

/// Request DTO for `lab_set_link_faults` (Block 42 "fault configuration").
///
/// `link_index` identifies the exact declaration because the bounded scenario
/// schema permits multiple links between the same node pair. `from`/`to` are
/// carried as a stale-selection guard: the backend rejects an edit if the
/// frontend's row no longer matches that declaration instead of mutating the
/// wrong link after a scenario replacement. Numeric text stays as strings
/// until the Rust command boundary so malformed values become structured Lab
/// validation errors rather than JavaScript coercions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LabSetLinkFaultsRequest {
    pub link_index: u32,
    pub from: String,
    pub to: String,
    pub latency_ms: String,
    pub jitter_ms: String,
    pub loss_permille: String,
}

#[cfg(test)]
mod tests {
    use super::{LabFileOutcomeDto, LabSetLinkFaultsRequest, LabStateDto};

    #[test]
    fn file_outcome_serializes_as_a_tagged_kind() {
        let json = serde_json::to_value(LabFileOutcomeDto::Saved).expect("serialize");
        assert_eq!(json["kind"], "saved");
        let json = serde_json::to_value(LabFileOutcomeDto::Cancelled).expect("serialize");
        assert_eq!(json["kind"], "cancelled");
    }

    #[test]
    fn empty_state_round_trips_through_json() {
        let state = LabStateDto {
            now_ms: "0".to_owned(),
            running: false,
            paused: false,
            nodes: Vec::new(),
            loaded_scenario: None,
            last_run: None,
        };
        let json = serde_json::to_string(&state).expect("serialize");
        let round_tripped: LabStateDto = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(round_tripped, state);
    }

    #[test]
    fn link_fault_request_uses_camel_case_and_preserves_numeric_text() {
        let request = LabSetLinkFaultsRequest {
            link_index: 3,
            from: "host".to_owned(),
            to: "listener".to_owned(),
            latency_ms: "125".to_owned(),
            jitter_ms: "9".to_owned(),
            loss_permille: "25".to_owned(),
        };
        let json = serde_json::to_value(&request).expect("serialize");
        assert_eq!(json["linkIndex"], 3);
        assert_eq!(json["latencyMs"], "125");
        assert_eq!(json["jitterMs"], "9");
        assert_eq!(json["lossPermille"], "25");
    }
}
